import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import Link from "next/link";
import paths from "@/paths";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div>
            <Link href={paths.home()}>Home</Link>
            <Link href={paths.topicShow("123")}>Topic</Link>
            <Link href={paths.postCreate("123")}>Create</Link>
            <Link href={paths.postShow("123", "123")}>Post</Link>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
